# Generated by Django 2.2 on 2020-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_del',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rule',
            name='is_del',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='is_del',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_del',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_del',
            field=models.IntegerField(default=1),
        ),
    ]
