# Generated by Django 2.2 on 2020-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201128_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_check',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
