"""empty message

Revision ID: 0bd132eb6432
Revises: 818ea537525f
Create Date: 2020-12-07 13:09:05.094107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bd132eb6432'
down_revision = '818ea537525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goods_ibfk_1', 'goods', type_='foreignkey')
    op.drop_column('goods', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('goods_ibfk_1', 'goods', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
