# Generated by Django 2.2 on 2020-11-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('cdata', models.DateField()),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='APP03.Class')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
