# Generated by Django 2.2 on 2020-12-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('is_del', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '组',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('is_del', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组',
                'db_table': 'rule_group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255, null=True)),
                ('register_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('login_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('login_num', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_check', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_check', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('is_del', models.IntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('is_del', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '用户——组中间表',
                'verbose_name_plural': '用户——组中间表',
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('rule_level', models.IntegerField()),
                ('parents_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('is_del', models.IntegerField(default=1)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_rule', to='App.Group')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'rule',
            },
        ),
    ]
