# Generated by Django 2.2 on 2020-12-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rule_id',
            field=models.ForeignKey(db_constraint=False, default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule_id', to='App.Rule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='group_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_rule', to='App.Group'),
        ),
    ]
