# Generated by Django 2.2 on 2020-12-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201207_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rule_id',
        ),
        migrations.AddField(
            model_name='group',
            name='rule_id',
            field=models.ManyToManyField(db_constraint=False, related_name='rule_id', to='App.Rule'),
        ),
        migrations.RemoveField(
            model_name='rule',
            name='group_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='group_id',
            field=models.ManyToManyField(db_constraint=False, related_name='group_rule', to='App.Group'),
        ),
    ]
