# Generated by Django 2.2 on 2020-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201207_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='group_id',
        ),
    ]
