# Generated by Django 2.2 on 2020-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='栏目')),
                ('link_url', models.URLField(verbose_name='链接')),
                ('index', models.IntegerField(verbose_name='位置')),
            ],
            options={
                'verbose_name': '栏目',
                'verbose_name_plural': '栏目',
                'db_table': 'tb_column',
                'ordering': ['index'],
            },
        ),
    ]
