# Generated by Django 2.2 on 2020-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
