# Generated by Django 2.2 on 2020-10-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='TimeTest',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date2', models.DateTimeField()),
            ],
            options={
                'db_table': 'time_test',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('parentsUrl', models.CharField(blank=True, db_column='parentsUrl', max_length=255, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=16, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Code')),
            ],
            options={
                'db_table': 'main',
            },
        ),
    ]
