# Generated by Django 2.2 on 2020-10-31 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('isdelete', models.IntegerField()),
                ('tid', models.IntegerField(max_length=10)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article_content',
            },
        ),
        migrations.CreateModel(
            name='ArticleTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'article_tab',
            },
            managers=[
                ('user_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('cdata', models.DateField()),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='App.Class')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.RemoveField(
            model_name='main',
            name='type',
        ),
        migrations.DeleteModel(
            name='TimeTest',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
