# Generated by Django 2.2 on 2020-11-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201031_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cid',
        ),
        migrations.AlterModelManagers(
            name='articletab',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
